---

###
### Lints all generic and json files in the whole git repository
###

name: linting
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - Linting
    name: "[ ${{ matrix.target }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Lint files
        run: |
          make _lint-files

      - name: "Check version"
        run: |
          make _lint-version

      - name: "Check binary name"
        run: |
          make _lint-bin-name

      - name: "Check package name"
        run: |
          make _lint-pkg-name

      - name: "Check description"
        run: |
          make _lint-description


